import { StyleSheet } from 'react-native';
import { colors, shadows } from './theme';

export const shoppingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.green,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  homeContent: {
    backgroundColor: colors.background,
    padding: 18,
    paddingBottom: 110,
  },
  homeHeader: {
    alignItems: 'center',
    backgroundColor: colors.green,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: -18,
    marginTop: -18,
    paddingBottom: 84,
    paddingHorizontal: 22,
    paddingTop: 28,
  },
  welcome: {
    color: '#DDF9E8',
    fontSize: 15,
  },
  userName: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  headerIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 22,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  summaryCard: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -64,
    padding: 20,
    ...shadows.card,
    elevation: 5,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  summaryValue: {
    color: colors.text,
    fontSize: 31,
    fontWeight: '800',
    marginTop: 4,
  },
  cartBadge: {
    alignItems: 'center',
    backgroundColor: colors.greenTintStrong,
    borderRadius: 16,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  statCard: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 14,
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 78,
    padding: 16,
    ...shadows.card,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 13,
  },
  statValue: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  quickTitle: {
    color: '#5D6571',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 18,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 18,
    ...shadows.floating,
  },
  primaryActionText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  outlineAction: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderColor: colors.greenText,
    borderRadius: 14,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 58,
  },
  outlineActionText: {
    color: colors.greenText,
    fontSize: 16,
    fontWeight: '800',
  },
  lightAction: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderColor: '#E6E9EE',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 58,
  },
  lightActionText: {
    color: '#343B48',
    fontSize: 16,
    fontWeight: '700',
  },
  listScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  greenTopBar: {
    alignItems: 'center',
    backgroundColor: colors.green,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 72,
    paddingHorizontal: 22,
  },
  topBarTitle: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
  },
  countBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 16,
    height: 30,
    justifyContent: 'center',
    minWidth: 34,
    paddingHorizontal: 8,
  },
  countBadgeText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  listContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 136,
  },
  formCard: {
    backgroundColor: colors.panel,
    borderRadius: 16,
    gap: 8,
    padding: 16,
    ...shadows.card,
  },
  formTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  photoButton: {
    alignItems: 'center',
    backgroundColor: colors.greenTint,
    borderColor: '#BFEFD2',
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 58,
  },
  photoButtonText: {
    color: colors.greenText,
    fontSize: 15,
    fontWeight: '800',
  },
  photoPreviewBox: {
    backgroundColor: colors.panelSoft,
    borderRadius: 14,
    gap: 10,
    padding: 10,
  },
  photoPreview: {
    backgroundColor: colors.greenTint,
    borderRadius: 12,
    height: 160,
    width: '100%',
  },
  photoActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  photoActionButton: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 12,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 44,
  },
  photoActionText: {
    color: colors.greenText,
    fontSize: 14,
    fontWeight: '800',
  },
  photoRemoveButton: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    width: 48,
  },
  label: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '700',
  },
  input: {
    backgroundColor: colors.panelSoft,
    borderColor: '#E1E5EA',
    borderRadius: 14,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  field: {
    flex: 1,
    gap: 8,
  },
  quantityField: {
    gap: 8,
    width: 88,
  },
  error: {
    color: colors.danger,
    fontSize: 14,
  },
  disabledButton: {
    opacity: 0.75,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 16,
    gap: 8,
    padding: 24,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  totalFooter: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    bottom: 74,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 20,
    paddingVertical: 14,
    position: 'absolute',
    right: 0,
  },
  footerLabel: {
    color: colors.muted,
    fontSize: 14,
  },
  footerTotal: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
  },
  floatingAddButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
    ...shadows.floating,
  },
  checkScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  checkContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 96,
  },
  checkCard: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 16,
    gap: 10,
    padding: 28,
  },
  checkItemCard: {
    backgroundColor: colors.panel,
    borderRadius: 16,
    gap: 14,
    padding: 16,
    ...shadows.card,
  },
  checkItemHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  checkItemName: {
    color: colors.text,
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  checkItemTotal: {
    color: colors.greenDark,
    fontSize: 16,
    fontWeight: '900',
  },
  checkItemRow: {
    flexDirection: 'row',
    gap: 10,
  },
  checkPill: {
    backgroundColor: colors.panelSoft,
    borderColor: '#E8EBEF',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    padding: 12,
  },
  checkPillLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
  },
  checkPillValue: {
    color: colors.greenDark,
    fontSize: 17,
    fontWeight: '900',
  },
  checkTotalCard: {
    backgroundColor: colors.green,
    borderRadius: 16,
    padding: 20,
  },
  checkTotal: {
    color: colors.white,
    fontSize: 34,
    fontWeight: '900',
  },
  cameraScreen: {
    backgroundColor: '#040914',
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 20,
  },
  cameraHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  cameraBackButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  cameraTitle: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  cameraFrame: {
    backgroundColor: '#111827',
    borderRadius: 24,
    flex: 1,
    maxHeight: 560,
    overflow: 'hidden',
    position: 'relative',
  },
  cameraPreview: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraGrid: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    justifyContent: 'center',
  },
  focusBox: {
    borderColor: colors.white,
    borderRadius: 8,
    borderWidth: 2,
    height: 126,
    width: 126,
  },
  cameraHint: {
    color: '#D8DEE9',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 24,
    maxWidth: 260,
    textAlign: 'center',
  },
  shutterButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.28)',
    borderRadius: 42,
    height: 84,
    justifyContent: 'center',
    marginTop: 22,
    width: 84,
  },
  shutterInner: {
    backgroundColor: colors.white,
    borderRadius: 32,
    height: 64,
    width: 64,
  },
  shutterHint: {
    color: '#8E96A3',
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  permissionBox: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderRadius: 18,
    gap: 10,
    marginTop: 110,
    padding: 22,
  },
  permissionTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  permissionText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  bottomTabs: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 74,
    justifyContent: 'space-around',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  tabButton: {
    alignItems: 'center',
    flex: 1,
    gap: 3,
    justifyContent: 'center',
  },
  tabLabel: {
    color: colors.mutedLight,
    fontSize: 11,
    fontWeight: '700',
  },
  activeTabLabel: {
    color: colors.green,
  },
  pressed: {
    opacity: 0.82,
  },
});
